services:
  - type: web
    name: niuniu-game
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false 